version: "3.8"
volumes:
  realtime-chat-data:
services:
  realtime-chat:
    build:
      context: .
    restart: always
    env_file: ./.env
    command: npm run dev
    container_name: ${API_CONTAINER_NAME}
    volumes:
      - .:/app/
    ports:
      - $NODE_LOCAL_PORT:$PORT
      - $SOCKET_PORT:$SOCKET_PORT
    depends_on:
      - mysqldb
    environment:
      DB_HOST: mysqldb
  mysqldb:
    image: mysql:${DB_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    container_name: ${DB_CONTAINER_NAME}
    env_file: ./.env
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - realtime-chat-mysql:/var/lib/mysql
      - realtime-chat-mysql_config:/etc/mysql
volumes:
  realtime-chat-mysql:
  realtime-chat-mysql_config:
  realtime-chat-data: